import * as XLSX from 'xlsx';
import type { Model, Settings, P6Activity, TestProgress, Snapshot } from '../engine/types';
import { p6PctComplete } from '../engine/compute';
import { fmtHours } from './format';

const d = (iso: string | null | undefined): Date | '' => (iso ? new Date(`${iso}T00:00:00`) : '');
const wsFrom = (rows: unknown[][]) => XLSX.utils.aoa_to_sheet(rows, { cellDates: true });

function extractSheet(acts: P6Activity[], withDerived: boolean): XLSX.WorkSheet {
  const header = ['Activity ID', 'Activity Name', 'Original Duration', 'Remaining Duration', 'Start', 'Finish'];
  const derived = ['Row_Type', 'Location', 'Seq_Code', 'Activity_Type', 'Exclude_Reason', 'Start_Date', 'Finish_Date', 'Actual?', 'P6_Pct_Complete', 'Actual_Start?'];
  const rows: unknown[][] = [withDerived ? [...header, ...derived] : [...header, 'BL_Start_Date', 'BL_Finish_Date']];
  for (const a of acts) {
    const base: unknown[] = [a.rawActivityId, a.activityName, a.originalDuration ?? '', a.remainingDuration ?? '', a.startRaw, a.finishRaw];
    if (withDerived) {
      rows.push([...base, a.rowType, a.location, a.rowType === 'ACTIVITY' ? a.seqCode : '', a.activityType, a.excludeReason ?? '', d(a.startDate), d(a.finishDate), a.actualFinish ? 'A' : '', a.rowType === 'ACTIVITY' ? p6PctComplete(a) : '', a.actualStart ? 'A' : '']);
    } else rows.push([...base, d(a.startDate), d(a.finishDate)]);
  }
  return wsFrom(rows);
}

/** Build the export workbook with the same sheet names and column layouts as the source workbook. Values only, no formulas. */
export function buildWorkbook(model: Model, settings: Settings, current: P6Activity[], baseline: P6Activity[], testProgress: TestProgress[], snapshots: Snapshot[]): XLSX.WorkBook {
  const wb = XLSX.utils.book_new();
  const s = model.summary;
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['T&C P6 Budget and S-Curve'],
    ['Generated by', 'T&C Budget desktop application'],
    ['Generated at', new Date().toISOString()],
    ['Note', 'All cells are values. The application, not this workbook, is the calculation engine.'],
    ['Spread', 'Curves are calendar-linear and ignore the P6 work calendar. Same-day activities credit in full on that day.'],
  ]), 'README');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Settings'], [],
    ['Default_Basis', settings.defaultBasis], ['Default_Crew', settings.defaultCrew], ['Default_Shift_Hours', settings.defaultShiftHours],
    ['Default_Complexity', settings.defaultComplexity], ['LOE_Duration_Days', settings.loeDurationDays],
    ['Status_Date', d(settings.statusDate)], ['Data_Date', d(settings.dataDate)],
  ]), 'Settings');
  XLSX.utils.book_append_sheet(wb, extractSheet(current, true), 'P6_Extract');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Location_Code', 'Activities', 'Complexity_Factor', 'Effective_Factor', 'Location_Name'],
    ...model.locations.map((l) => [l.code, l.count, l.location.complexityFactor ?? '', l.effectiveFactor, l.location.name ?? '']),
  ]), 'Locations');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Match_Key', 'Count', 'Total_P6_Days', 'Discipline', 'Include_Override', 'Include', 'Basis', 'Crew_Size', 'Shift_Hours', 'Duration_Shifts', 'Basis_Eff', 'Crew_Eff', 'Shift_Eff', 'Rate_Status', 'Std_Hours_If_RATE', 'Notes'],
    ...model.library.map((l) => [l.matchKey, l.count, l.totalP6Days, l.entry.discipline ?? '', l.entry.includeOverride ?? '', l.include, l.entry.basis ?? '', l.entry.crewSize ?? '', l.entry.shiftHours ?? '', l.entry.durationShifts ?? '', l.basisEff, l.crewEff, l.shiftEff, l.rateStatus, l.stdHoursIfRate ?? 'n/a', l.entry.notes ?? '']),
  ]), 'Activity_Library');
  const checks = new Map(model.testProgressChecks.map((c) => [c.activityId, c]));
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['P6_Activity_ID', 'Tests_Total', 'Tests_Complete', 'Pct_Override', 'Pct_Effective', 'Activity_Name_Check', 'Budget_Status_Check', 'Test_Start_Override', 'Test_End_Override'],
    ...testProgress.map((t) => {
      const c = checks.get(t.activityId);
      return [t.activityId, t.testsTotal ?? '', t.testsComplete ?? '', t.pctOverride ?? '', c?.pctEffective ?? '', c?.activityName ?? 'ID NOT IN EXTRACT', c?.status ?? '', d(t.testStartOverride), d(t.testEndOverride)];
    }),
  ]), 'Test_Progress');
  XLSX.utils.book_append_sheet(wb, extractSheet(baseline, false), 'Baseline_Extract');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Row', 'P6_Activity_ID', 'Location', 'Seq_Code', 'Match_Key', 'Rate_Status', 'Status', 'Basis', 'LOE_Flag', 'Complexity', 'Std_Hours', 'Override_Hours', 'Budget_Hours', 'Baseline_Start', 'Baseline_Finish', 'Baseline_Source', 'Current_Start', 'Current_Finish', 'Pct_Complete', 'Pct_Source', 'Earned_Hours', 'Remaining_Hours', 'Match_Tier', 'Phase', 'Work_Type', 'Activity_Name', 'Activity_Type', 'Discipline', 'Earn_Start', 'Earn_End', 'Earn_Window_Source'],
    ...model.rows.map((r, i) => [i + 2, r.activity.rawActivityId, r.location, r.seqCode, r.matchKey, r.rateStatus, r.status, r.basis ?? '', r.loeFlag ? 'LOE?' : '', r.complexity ?? '', r.stdHours ?? '', r.overrideHours ?? '', r.budgetHours, d(r.baselineStart), d(r.baselineFinish), r.baselineSource, d(r.currentStart), d(r.currentFinish), r.pctComplete, r.pctSource, r.earnedHours, r.remainingHours, r.matchTier ?? '', r.phaseName, r.workType, r.activity.activityName, r.activityType, r.discipline, d(r.earnStart), d(r.earnEnd), r.earnWindowSource]),
  ]), 'Budget_Master');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Status_Date', 'P6_Activity_ID', 'Pct_Complete', 'Budget_Hours', 'Earned_Hours', 'Taken_At', 'Note'],
    ...snapshots.flatMap((sn) => sn.lines.map((l) => [d(sn.statusDate), l.activityId, l.pctComplete, l.budgetHours, l.earnedHours, sn.takenAt, sn.note ?? ''])),
  ]), 'Status_History');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Status_Date', 'P6_Activity_ID', 'Pct_Complete', 'Source'],
    ...model.rows.filter((r) => r.status === 'IN BUDGET').map((r) => [d(settings.statusDate), r.activityId, r.pctComplete, r.pctSource]),
  ]), 'Snapshot');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Budget Summary'], [],
    ['Extract rows', s.extractRows], ['  WBS summary rows', s.wbsRows, 'Auto-excluded'], ['  Real activities', s.activities], [],
    ['Locations discovered', s.locations], ['Activity types discovered', s.activityTypes], ['  Types still on defaults', s.typesOnDefaults], ['  Types missing shift count', s.typesNeedingShifts], [],
    ['Activities in budget', s.inBudget], ['Excluded by library', s.excluded], ['Deleted or cancelled', s.deletedOrCancelled], ['Needing REVIEW', s.review], [],
    ['Total budget man-hours', s.totalBudgetHours], ['Earned man-hours', s.earnedHours], ['Remaining man-hours', s.remainingHours], ['Overall percent complete', s.pctComplete], [],
    ['Dates from baseline import', s.baselineMatched], ['Dates falling back to current', s.baselineFallback], ['Activities with no dates at all', s.noDates], [],
    ['Progress from test cases', s.pctFromTests], ['Progress from P6 duration', s.pctFromP6], ['Latest status date', s.latestStatusDate ? d(s.latestStatusDate) : 'none yet'], [],
    ['Earned-value data quality'], ['Test_Progress rows keyed', s.testProgressKeyed], ['  not matching a budgeted activity', s.testProgressNotMatching], ['  using a direct Pct_Override', s.testProgressUsingOverride], [],
    ['Activities started, not finished', s.inProgress], ['Activities with P6 actual dates', s.p6Actual], ['Activities on a test window', s.testWindow], ['Activities not started', s.notStarted],
  ]), 'Summary');
  XLSX.utils.book_append_sheet(wb, wsFrom([
    ['Period_End', 'Planned_Cum_Hours', 'Forecast_Cum_Hours', 'Earned_Cum_Hours (actual dates)', 'Planned_Pct', 'Earned_Pct', 'Reported_At_Status'],
    ...model.curve.map((c) => [d(c.periodEnd), c.planned, c.forecast, c.earned ?? '', c.plannedPct, c.earnedPct ?? '', c.snapshot ?? '']),
  ]), 'S_Curve');
  return wb;
}

export function workbookBytes(wb: XLSX.WorkBook): Uint8Array {
  return new Uint8Array(XLSX.write(wb, { type: 'array', bookType: 'xlsx', cellDates: true }) as ArrayBuffer);
}

export function curveCsv(model: Model): string {
  const lines = ['Period_End,Planned_Cum_Hours,Forecast_Cum_Hours,Earned_Cum_Hours,Planned_Pct,Earned_Pct,Snapshot_Earned_Hours'];
  for (const c of model.curve) {
    lines.push([c.periodEnd, c.planned.toFixed(2), c.forecast.toFixed(2), c.earned === null ? '' : c.earned.toFixed(2), c.plannedPct.toFixed(4), c.earnedPct === null ? '' : c.earnedPct.toFixed(4), c.snapshot === null ? '' : c.snapshot.toFixed(2)].join(','));
  }
  return lines.join('\r\n') + '\r\n';
}

/** Rasterise the chart's SVG to PNG bytes. */
export async function svgToPng(svg: SVGSVGElement, scale = 2): Promise<Uint8Array> {
  const clone = svg.cloneNode(true) as SVGSVGElement;
  const w = svg.clientWidth || Number(svg.getAttribute('width')) || 900;
  const h = svg.clientHeight || Number(svg.getAttribute('height')) || 400;
  clone.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  clone.setAttribute('width', String(w));
  clone.setAttribute('height', String(h));
  clone.style.fontFamily = 'system-ui, Segoe UI, sans-serif';
  const xml = new XMLSerializer().serializeToString(clone);
  const url = URL.createObjectURL(new Blob([xml], { type: 'image/svg+xml;charset=utf-8' }));
  try {
    const img = await new Promise<HTMLImageElement>((resolve, reject) => {
      const i = new Image();
      i.onload = () => resolve(i);
      i.onerror = () => reject(new Error('Could not render the chart image'));
      i.src = url;
    });
    const canvas = document.createElement('canvas');
    canvas.width = w * scale;
    canvas.height = h * scale;
    const ctx = canvas.getContext('2d')!;
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.scale(scale, scale);
    ctx.drawImage(img, 0, 0);
    const blob = await new Promise<Blob | null>((r) => canvas.toBlob(r, 'image/png'));
    if (!blob) throw new Error('PNG encoding failed');
    return new Uint8Array(await blob.arrayBuffer());
  } finally {
    URL.revokeObjectURL(url);
  }
}

export function downloadBytes(name: string, bytes: Uint8Array, type: string): void {
  const url = URL.createObjectURL(new Blob([bytes as BlobPart], { type }));
  const a = document.createElement('a');
  a.href = url;
  a.download = name;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export function stamp(): string {
  return new Date().toISOString().slice(0, 16).replace(/[:T]/g, '-');
}

export const hoursLabel = (n: number) => fmtHours(n);
